- Gemfile
- Gemfile.lock
- app/models/article.rb
- app/models/executor.rb
- app/models/funeral.rb
- app/models/will.rb
- db/migrate/20220523175805_create_funerals.rb
- db/migrate/20220523175909_create_executors.rb
- db/migrate/20220523180210_create_articles.rb
- db/migrate/20220523180535_add_column_to_users.rb
- db/migrate/20220524020806_create_wills.rb
- db/seeds.rb
- test/models/article_test.rb
- test/models/executor_test.rb
- test/models/funeral_test.rb
- test/models/will_test.rb
Validations are very basic right now but there's enough to test out models and use them in the app.
> models with very basic associations

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/schema.rb
- db/seeds.rb
The data types might need to be changed. We can do this as we come across them hopefully
> can seed wills kinda

- app/models/user.rb
temporary fix. validates only by email so if you want check new sign-ins knock yourself out.
> fixed user model validations

- app/controllers/funerals_controller.rb
- app/policies/funeral_policy.rb
> edit pundit

- app/assets/stylesheets/components/_card-contents.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/funerals/arrangement.html.erb
- app/views/funerals/index.html.erb
- app/views/funerals/memory.html.erb
- app/views/funerals/music.html.erb
- app/views/funerals/no_invite.html.erb
- app/views/funerals/representative.html.erb
- app/views/funerals/sending_message.html.erb
- app/views/funerals/ten_words.html.erb
- app/views/funerals/unaware_state.html.erb
> design show page

- app/controllers/wills_controller.rb
- app/policies/will_policy.rb
- app/views/wills/index.html.erb
Needs styling but journey is mostly complete.
> will create and show functional

- app/assets/stylesheets/components/_banner.scss
- app/views/pages/home.html.erb
> change landing button

- app/views/wills/index.html.erb
- db/seeds.rb
Should be working largely as intended...
> executor seeds ready

- app/views/wills/index.html.erb
the /wills page should show properly now
> fixed wills show page

- db/seeds.rb
> altered seeds a bit. fewer words to choose from

- app/controllers/funerals_controller.rb
- app/models/funeral.rb
- app/models/user.rb
- app/policies/funeral_policy.rb
- app/views/funerals/index.html.erb
- app/views/funerals/representative.html.erb
- app/views/funerals/ten_words.html.erb
- config/routes.rb
- db/seeds.rb
fix cotroller and ten-words page
> fix cotroller and ten-words page

- db/seeds.rb
> change password into original

- app/assets/config/manifest.js
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_will-card.scss
- app/javascript/packs/application.js
- app/views/wills/edit.html.erb
- app/views/wills/show.html.erb
- db/seeds.rb
slight fade in added to text. SCSS file added too.
> added style to will show

- app/assets/config/manifest.js
- app/assets/stylesheets/components/_will-card.scss
- app/javascript/controllers/make_pdf_controller.js
- app/views/layouts/application.html.erb
- app/views/wills/show.html.erb
- package.json
- yarn.lock
This is a fix for some of the will pages. There's also and HTML to PDF function now.
> added pdf export tool

- app/assets/stylesheets/components/_card-contents.scss
- app/views/funerals/arrangement.html.erb
- app/views/funerals/memory.html.erb
- app/views/funerals/music.html.erb
- app/views/funerals/no_invite.html.erb
- app/views/funerals/representative.html.erb
- app/views/funerals/sending_message.html.erb
- app/views/funerals/unaware_state.html.erb
> edit cards

- app/javascript/packs/application.js
- db/seeds.rb
one extra user for pitch. check seed file for login details
> altered seeds. added user for pitch

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/config/_fonts.scss
> default fonts added

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card-contents.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/funerals/ten_words.html.erb
- app/views/pages/home.html.erb
> change button

- app/views/wills/show.html.erb
> change button in will page

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
Border radius on cards adjusted to 6px.
> rounded edges on cards

- app/assets/stylesheets/components/_flip.scss
- app/controllers/funerals_controller.rb
- app/models/funeral.rb
- app/views/funerals/index.html.erb
- app/views/funerals/memory.html.erb
- config/storage.yml
> add cloudinary upload

- app/assets/stylesheets/components/_card-contents.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_tags.scss
- app/models/funeral.rb
- app/views/funerals/index.html.erb
- app/views/funerals/memory.html.erb
- app/views/funerals/representative.html.erb
- app/views/funerals/sending_message.html.erb
- app/views/funerals/unaware_state.html.erb
design button other show pages
> design button other show pages

- app/controllers/funerals_controller.rb
- app/views/funerals/arrangement.html.erb
- app/views/funerals/index.html.erb
- app/views/funerals/memory.html.erb
- app/views/funerals/music.html.erb
- app/views/funerals/no_invite.html.erb
- app/views/funerals/sending_message.html.erb
- app/views/funerals/ten_words.html.erb
- app/views/funerals/unaware_state.html.erb
> edit button in index page

- config/environments/production.rb
- config/initializers/smtp.rb
I forgot we needed a mailer for the development site.
> development mailer set up

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/views/funerals/index.html.erb
> change index style

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
> meta tags configuration

- app/assets/stylesheets/components/_card.scss
- app/views/wills/index.html.erb
- config/environments/production.rb
I change wills page style and added articles
> change wills page

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_ten_words.scss
- app/views/funerals/ten_words.html.erb
stuck margin on the first funeral question box using the most unnecessary partial ever created.
> fixed the style for the funeral questions

- app/assets/stylesheets/components/_banner.scss
- app/controllers/wills_controller.rb
- app/views/wills/new.html.erb
> fix button and landing page

- app/models/user.rb
- app/views/devise/registrations/new.html.erb
Only email is validating in sign up yet though.
> added registration fields to user sign up

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_flip.scss
- app/javascript/packs/application.js
- app/views/wills/index.html.erb
change hover and make flip smaller
> change hover and make flip smaller

- app/views/wills/show.html.erb
make will and email input bigger in the show page
> change will show page

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_ldBar.scss
- app/javascript/controllers/loading_controller.js
- app/views/wills/show.html.erb
change button color in will's show page
> change button color of will show page

- app/assets/stylesheets/components/_alert.scss
- app/views/wills/index.html.erb
- app/views/wills/show.html.erb
change word to my-will in wills page
> change word to my-will

- app/views/wills/index.html.erb
change the words in index page
> change the words in index page
